export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_DETAILS = "AUTH_DETAILS";
export const STATE = {
  USER: "USER",
  TRANSFERS: "TRANSFERS",
  PAYROLL_EMPLOYEES: "PAYROLL_EMPLOYEES",
  USERS: "USERS",
  COMPANIES: "COMPANIES",
  DASHBOARD: "DASHBOARD",
  SNACKBAR: "SNACKBAR",
  PAYROLLS: "PAYROLLS",
  AUTH_TOKENS: "AUTH_TOKENS",
  BANKS: "BANKS",
};
